// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHVRfaFxFtWXLJkOAsIGUWhojoOknLVbI',
    appId: '1:877727777718:web:cb33cbed4e35b838947717',
    messagingSenderId: '877727777718',
    projectId: 'poston-53a48',
    authDomain: 'poston-53a48.firebaseapp.com',
    storageBucket: 'poston-53a48.firebasestorage.app',
    measurementId: 'G-SH1LXMPS54',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXmF16EkJaHQ9fzutvmc9mMvPDzeg6T6w',
    appId: '1:877727777718:android:001d83cda4291827947717',
    messagingSenderId: '877727777718',
    projectId: 'poston-53a48',
    storageBucket: 'poston-53a48.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBddV0LzOPY3-M8GeNWTB-hnMS2jqTGsms',
    appId: '1:877727777718:ios:5dd320f6d4851e6b947717',
    messagingSenderId: '877727777718',
    projectId: 'poston-53a48',
    storageBucket: 'poston-53a48.firebasestorage.app',
    iosBundleId: 'com.example.postonApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBddV0LzOPY3-M8GeNWTB-hnMS2jqTGsms',
    appId: '1:877727777718:ios:5dd320f6d4851e6b947717',
    messagingSenderId: '877727777718',
    projectId: 'poston-53a48',
    storageBucket: 'poston-53a48.firebasestorage.app',
    iosBundleId: 'com.example.postonApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDHVRfaFxFtWXLJkOAsIGUWhojoOknLVbI',
    appId: '1:877727777718:web:7dc5de9400511594947717',
    messagingSenderId: '877727777718',
    projectId: 'poston-53a48',
    authDomain: 'poston-53a48.firebaseapp.com',
    storageBucket: 'poston-53a48.firebasestorage.app',
    measurementId: 'G-82B94X2WZR',
  );
}
